version: '2'
services: 
  mysql:
    hostname: mysql
    container_name: mysql-10.3.15-alpine
    build: ./mysql
    ports:
      - 3308:3306
    networks:
      staticnymc:
        ipv4_address: 172.20.1.3
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/app/mysql
      - ./mysql/backup:/backup
      - /etc/localtime:/etc/localtime
    restart: always
  redis_master:
    hostname: redis-master
    container_name: redis-5.0.7-alpine-master
    build: ./redis-master
    ports:
      - 6379:6379
    networks:
      staticnymc:
        ipv4_address: 172.20.1.4
    volumes:
      - ./redis-master/data:/data
      - ./redis-slave/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    restart: always
  redis_slave:
    hostname: redis-slave
    container_name: redis-5.0.7-alpine-slave
    build: ./redis-slave
    ports:
      - 6380:6380
    networks:
      staticnymc:
        ipv4_address: 172.20.1.5
    volumes:
      - ./redis-slave/data:/data
      - ./redis-slave/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    restart: always
  tomcat:
    hostname: tomcat
    container_name: tomcat-8.5.41-alpine
    depends_on:
      - mysql
      - redis_master
      - redis_slave
      - activemq
    build: ./tomcat
    ports:
      - 8080:8080
    networks:
      staticnymc:
        ipv4_address: 172.20.1.2
    volumes:
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./tomcat/logs:/usr/local/tomcat/logs
      - /etc/localtime:/etc/localtime
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    restart: always
  activemq:
    hostname: activemq
    container_name: activemq-5.14.3-alpine
    build: ./activemq
    ports:
      - 8161:8161
      - 61616:61616
    networks:
      staticnymc:
        ipv4_address: 172.20.1.6
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/logs:/var/log/activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 2048
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    restart: always
networks:
  staticnymc:
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
